language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.2
  - 1.3
  - 1.4

before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="BinaryProvider", rev="mg/fix-write-deps-isolation"))'

notifications:
  email: false
codecov: true

